# Generated by Django 3.1.2 on 2020-10-14 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='Other_activities',
            new_name='OTHER',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='id',
        ),
        migrations.AddField(
            model_name='sighting',
            name='S_ID',
            field=models.CharField(default='abcd', help_text='Unique Sighting ID', max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
